---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-secret-crud
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","create","update","delete","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-secret-admission-crud-binding
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno-secret-crud
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-secret-background-crud-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno-secret-crud
  apiGroup: rbac.authorization.k8s.io
---