apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policy-generate-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: kyverno-policy-generate-secret
spec:
  destination:
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://manifests
    targetRevision: HEAD
    path: "."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true