# Inspired from: https://piotrminkowski.com/2022/12/09/manage-multiple-kubernetes-clusters-with-argocd/
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secret
spec:
  generateExistingOnPolicyUpdate: true
  rules:
    - name: sync-secret
      match:
        any:
          - resources:
              names:
                - "vc-*" # Prefix of the secret created for each vcluster
              kinds:
                - Secret
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - default
                - kube-public
                - kyverno
      context:
        - name: namespace
          variable:
            value: "{{ request.object.metadata.namespace }}"
        - name: name
          variable:
            value: "{{ request.object.metadata.name }}"
        - name: ca
          variable:
            value: "{{ request.object.data.\"certificate-authority\" }}"
        - name: cert
          variable:
            value: "{{ request.object.data.\"client-certificate\" }}"
        - name: key
          variable:
            value: "{{ request.object.data.\"client-key\" }}"
        - name: vclusterName
          variable:
            value: "{{ replace_all(namespace, 'vcluster-', '') }}"
            jmesPath: 'to_string(@)'
      generate:
        kind: Secret
        apiVersion: v1
        name: "{{ vclusterName }}"
        namespace: argocd
        synchronize: true
        data:
          kind: Secret
          metadata:
            labels:
              argocd.argoproj.io/secret-type: cluster
          stringData:
            name: "{{ vclusterName }}"
            server: "https://{{ vclusterName }}.cnoe.localtest.me:8443"
            config: |
              {
                "tlsClientConfig": {
                  "insecure": false,
                  "caData": "{{ ca }}",
                  "certData": "{{ cert }}",
                  "keyData": "{{ key }}"
                }
              }