# Inspired from: https://piotrminkowski.com/2022/12/09/manage-multiple-kubernetes-clusters-with-argocd/
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secret
spec:
  rules:
    - name: sync-secret
      match:
        any:
          - resources:
              # DON'T WORK using "vc-*" as key matching name - https://github:com/kyverno/kyverno/discussions/12614
              # The use of variables like {{ vclusterName }} in the match block is not allowed by Kyverno.
              # Variables can only be used in the generate or context sections, so match blocks must rely on static values or label selectors.
              # Additionally, attempting to use wildcards in the names field (e.g., "vc-*") doesn't work either, as Kyverno expects exact names there.
              # To match secrets dynamically, you must list full names or switch to using labels.
              kinds:
                - Secret
              selector:
                matchExpressions:
                  - { key: vcluster-name, operator: In, values: [ "worker-1", "worker-2", "worker-3", "worker-4", "worker-5" ] }
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - default
                - kube-public
                - kyverno
                - argocd
      context:
        - name: namespace
          variable:
            value: "{{ request.object.metadata.namespace }}"
        - name: name
          variable:
            value: "{{ request.object.metadata.name }}"
        - name: ca
          variable:
            value: "{{ request.object.data.\"certificate-authority\" }}"
        - name: cert
          variable:
            value: "{{ request.object.data.\"client-certificate\" }}"
        - name: key
          variable:
            value: "{{ request.object.data.\"client-key\" }}"
        - name: vclusterName
          variable:
            value: "{{ replace_all(namespace, 'vcluster-', '') }}"
            jmesPath: 'to_string(@)'
      generate:
        generateExisting: true
        kind: Secret
        apiVersion: v1
        name: "{{ vclusterName }}"
        namespace: argocd
        synchronize: true
        data:
          kind: Secret
          metadata:
            labels:
              argocd.argoproj.io/secret-type: cluster
              newClusterName: "{{ vclusterName }}"
          stringData:
            name: "{{ vclusterName }}"
            server: "https://{{ vclusterName }}.cnoe.localtest.me:8443"
            config: |
              {
                "tlsClientConfig": {
                  "insecure": false,
                  "caData": "{{ ca }}",
                  "certData": "{{ cert }}",
                  "keyData": "{{ key }}"
                }
              }